pr_27
sns-seb/pr_decoration pull request #32
Opened 2017-12-07 16:29 UTC by sns-seb

2017-12-07 16:30 UTC, sns-seb2 requested changes
SonarQube analysis found issues:
![Bug](https://sonarsource.github.io/sonar-github/bug.png 'Bug') Bugs: 2
![Vulnerability](https://sonarsource.github.io/sonar-github/vulnerability.png 'Vulnerability') Vulnerabilities: 0
![Code Smell](https://sonarsource.github.io/sonar-github/code_smell.png 'Code Smell') Code Smells: 1

[See all issues in SonarQube](http://localhost:9000/project/issues?id=org.sonarqube%3Apr-decoration&branch=pr_27&resolved=false)

2017-12-07 16:30 UTC, sns-seb2 commented on src/main/java/org/sonarqube/A.java
>      return message;
###AWAx0E7PPHgtnqdCFELC###
org.sonarqube:pr-decoration:src/main/java/org/sonarqube/A.java:BRANCH:pr_27@9
The return value of "length" must be used.

2017-12-07 16:30 UTC, sns-seb2 commented on src/main/java/org/sonarqube/A.java
> +    message = null;
###AWAx0E7PPHgtnqdCFELB###
org.sonarqube:pr-decoration:src/main/java/org/sonarqube/A.java:BRANCH:pr_27@6
Complete the task associated to this TODO comment.

2017-12-07 16:30 UTC, sns-seb2 commented on src/main/java/org/sonarqube/A.java
>      return message;
###AWAx0E7PPHgtnqdCFELD###
org.sonarqube:pr-decoration:src/main/java/org/sonarqube/A.java:BRANCH:pr_27@9
A "NullPointerException" could be thrown; "message" is nullable here.

2017-12-08 08:37 UTC, sns-seb commented
foo

[sq-issue-key]: issue key

2017-12-11 08:55 UTC, closed without merging